name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      pact-broker:
        image: pactfoundation/pact-broker
        ports:
          - 9292:9292
        options: >-
          --health-cmd "wget --spider http://localhost:9292 || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run PyTest (Unit Tests)
      run: |
        pytest

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Node dependencies
      run: npm ci

    - name: Run Cypress (E2E Tests)
      run: npx cypress run

    - name: Run Postman API tests with Newman
      run: |
        npm install -g newman
        newman run api-tests.postman_collection.json

    - name: Run Pact Contract Tests
      run: |
        npm install -g @pact-foundation/pact
        node pact/provider/pactSetup.test.js

    - name: Run k6 Performance Test
      uses: grafana/k6-action@v0.2.0
      with:
        filename: k6-test.js
