name: Full Test Suite

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Node.js dependencies
        run: npm install

      - name: Start frontend server
        run: |
          npx serve demo-testing-framework/app -l 5500 &
          npx wait-on http://localhost:5500

      - name: Run Cypress E2E tests
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          wait-on: 'http://localhost:5500'
          command: npx cypress run

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Flask API server
        run: |
          nohup python app/api.py --host=0.0.0.0 &
          sleep 10

      - name: Wait for Flask API
        run: |
          sudo apt-get update && sudo apt-get install -y curl
          until curl --output /dev/null --silent --head --fail http://localhost:5000/api/health; do
            echo "Waiting for Flask API..."
            sleep 5
          done

      - name: Run Postman API tests with Newman
        run: npx newman run api-tests.postman_collection.json

      - name: Run Contract Tests (Consumer)
        run: npm run test:contract

      - name: Run Contract Verification (Provider)
        run: npm run test:verify

      - name: Run Python unit tests
        run: pytest demo-testing-framework/tests/test_calculator.py
