name: Cypress Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Node.js dependencies
        run: npm install

      - name: Install serve and wait-on
        run: npm install -g serve wait-on

      - name: Start frontend server
        run: |
          npx serve demo-testing-framework/app -l 5500 &
          npx wait-on http://localhost:5500

      - name: Run Cypress tests
        run: | 
          chmod +x ./node-modules/.bin/cypress
          npx cypress run

      - name: Start Flask API server (background)
        run: |
          pip install -r requirements.txt
          nohup python app/api.py &

      - name: Wait for Flask API to be ready
        run: |
          sudo apt-get install -y curl
          until curl --output /dev/null --silent --head --fail http://127.0.0.1:5000/api/health; do
            echo "Waiting for Flask API to start..."
            sleep 3
          done

      - name: Run API tests (Postman/Newman)
        run: npx newman run api-tests.postman_collection.json

      - name: Run contract tests (consumer)
        run: npm run test:contract

      - name: Run contract verification (provider)
        run: npm run test:verify

      - name: Run Python unit tests
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pytest demo-testing-framework/tests/test_calculator.py
