name: Run All Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Start Flask app in background
      run: |
        python app/api.py &
        sleep 5

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Cypress & Newman
      run: |
        npm install
        npm install -g newman

    - name: Run Unit Tests with PyTest
      run: |
        pytest

    - name: Run API Tests with Newman
      run: |
        newman run api-tests.postman_collection.json

    - name: Run Cypress E2E Tests
      uses: cypress-io/github-action@v6
      with:
        start: npx serve app -l 5500
        wait-on: 'http://localhost:5500/index.html'
        wait-on-timeout: 60
