name: Cypress Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install serve package
        run: npm install -g serve

      - name: Start local server
        run: |
          npx serve app -l 5500 &
          sleep 5 # wait for server to boot

      - name: Run Cypress tests
        run: npx cypress run
