name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Start local server
        run: npx serve app -l 5500 &
        env:
          NODE_ENV: development

      - name: Wait for server to be ready
        run: npx wait-on http://localhost:5500/index.html

      - name: Run Cypress tests
        run: npx cypress run
